/*
 * This Java source file was generated by the Gradle 'init' task.
 */

// import static org.junit.Assert.assertEquals;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotEquals;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.PrintStream;
import java.util.List;

import org.junit.jupiter.api.Test;


public class PopulationCounterTest {
 
    @Test
    public void testSomeLibraryMethod() throws Exception {

        // Setup
        String expected = "World population is: 1,347,982,728\n";

        // https://stackoverflow.com/questions/8708342/redirect-console-output-to-string-in-java
        ByteArrayOutputStream baos = new ByteArrayOutputStream();
        PrintStream ps = new PrintStream(baos);
        PrintStream old = System.out;
        System.setOut(ps);

        // Exercise
        PopulationCounter.main(new String[] {"./data/worldcitiespop.csv"});

        // Assert
        System.out.flush();
        String output = baos.toString();
        assertEquals(expected, output );

        // Teardown
        System.setOut(old);
    }


// ad,aixas,Aix�s,06,,42.4833333,1.4666667

    // our data is not null.
    @Test
    public void testReadFile() throws IOException{

        ReadFile readFile = new ReadFile(); 
        List<String> myList = readFile.getLines("./data/worldcitiespop.csv");

        assertNotEquals(null, myList);
    }


    @Test
    public void testParseData() throws IOException{

        ReadFile readFile = new ReadFile(); 
        List<String> lines =  readFile.getLines("./data/worldcitiespop.csv");
        ParseData myParseData = new ParseData();
        List<String> parsedData = myParseData.parseMyData(lines);

         // Assert
         assertEquals(20430, parsedData);
            // assertEquals(2043, 2043);



    }




    // A separate class reads from the CSV file.

    // @Test
    // public void testReadFile (){
    //     ReadFile readFile = mock (ReadFile.)

    // }




}
